package ws.ejemplo.cliente.comunicacion;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SaludoXML", targetNamespace = "urn:SaludoXMLwsdl", wsdlLocation = "http://localhost/servicio.php?wsdl")
public class SaludoXML
    extends Service
{

    private final static URL SALUDOXML_WSDL_LOCATION;
    private final static WebServiceException SALUDOXML_EXCEPTION;
    private final static QName SALUDOXML_QNAME = new QName("urn:SaludoXMLwsdl", "SaludoXML");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost/servicio.php?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SALUDOXML_WSDL_LOCATION = url;
        SALUDOXML_EXCEPTION = e;
    }

    public SaludoXML() {
        super(__getWsdlLocation(), SALUDOXML_QNAME);
    }

    public SaludoXML(WebServiceFeature... features) {
        super(__getWsdlLocation(), SALUDOXML_QNAME, features);
    }

    public SaludoXML(URL wsdlLocation) {
        super(wsdlLocation, SALUDOXML_QNAME);
    }

    public SaludoXML(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SALUDOXML_QNAME, features);
    }

    public SaludoXML(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SaludoXML(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SaludoXMLPortType
     */
    @WebEndpoint(name = "SaludoXMLPort")
    public SaludoXMLPortType getSaludoXMLPort() {
        return super.getPort(new QName("urn:SaludoXMLwsdl", "SaludoXMLPort"), SaludoXMLPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SaludoXMLPortType
     */
    @WebEndpoint(name = "SaludoXMLPort")
    public SaludoXMLPortType getSaludoXMLPort(WebServiceFeature... features) {
        return super.getPort(new QName("urn:SaludoXMLwsdl", "SaludoXMLPort"), SaludoXMLPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SALUDOXML_EXCEPTION!= null) {
            throw SALUDOXML_EXCEPTION;
        }
        return SALUDOXML_WSDL_LOCATION;
    }

}
